---
title: "RF_variable selection"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(foreign)
library(tidyverse)
library(tidymodels)
library(vip)
```

```{r}
dbf <- read.dbf("output.dbf")
df <- tibble(dbf)

df[df==-99997] <- NA

df <- df %>% drop_na()
set.seed(06042022)

# drop distance metrics (not real demographics)
df <- df[!(substring(names(df),1,2) == "AV")]
df <- df[!(substring(names(df),1,2) == "AF")]

# drop pc4 data, we don't want to use spatial data here
df <- select(df, -PC4)

data_split <- initial_split(df, prop=3/4)
train_data <- training(data_split)
test_data_very_secret <- testing(data_split) # can be used for verification
#glimpse(train_data)

cores <- parallel::detectCores()
cores
```

```{r}
# Random forests
rf_mod <- 
  rand_forest() %>% 
  set_engine("ranger", num.threads=cores, importance = "impurity") %>% 
  set_mode("regression")

# K-Fold cross validation
folds <- vfold_cv(df, v = 10, repeats=10)

# Random trees workflow
random_trees_wf <- 
  workflow() %>%
  add_model(rf_mod) %>%
  add_formula(nox_mean ~ . - no2_mean - pm10_mean - pm25_mean) # Select the pollutant here
collect_notes(fit_rs)[1,]$note

fit_rs <- 
   random_trees_wf %>%  
   fit_resamples(folds)

collect_metrics(fit_rs)
last_rf_fit <- 
  random_trees_wf %>% 
  last_fit(data_split)

last_rf_fit %>% 
  pluck(".workflow", 1) %>%   
  extract_fit_parsnip() %>% 
  vip(num_features = 20) + ggtitle("NOX")
```
